apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-node
  labels:
    app: server-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-node
  template:
    metadata:
      labels:
        app: server-node
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: pvc1
      containers:
        - name: server-node
          image: vodo100801/server-node:v1
          imagePullPolicy: Always